services:
  ebook-book:
    build: .
    container_name: ebook-book
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - ebook-net

networks:
  ebook-net:
    external: true

